spring:
  application:
    name: abeflow-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/abeflow
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: abeflow_user
    password: abeflow_pass

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    br.com.abegg.abeflow: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

abeflow:
  api:
    version: v1
    base-path: /api/v1
